export const GET_PROPRIETE = "GET_PROPRIETE";
export const UPDATE_PROPRIETE = "UPDATE_PROPRIETE";
export const SEE_PROPRIETE = "SEE_PROPRIETE";

export const GET_DOSSIER = "GET_DOSSIER";
export const SEE_DOSSIER = "SEE_DOSSIER";

export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const SEE_USER = "SEE_USER";

export const GET_MY_DATA = "GET_MY_DATA";
export const GET_LOGOUT = "GET_LOGOUT";
export const GET_ADRESSE_SITE = "GET_ADRESSE_SITE";

export const TOOGLE_LOADER = "TOOGLE_LOADER";
export const TOOGLE_CLIENT_ADD_MODAL = "TOOGLE_CLIENT_ADD_MODAL";
export const TOOGLE_CHASSEUR_ADD_MODAL = "TOOGLE_CHASSEUR_ADD_MODAL";
export const TOOGLE_PROPRIETE_ADD_MODAL = "TOOGLE_PROPRIETE_ADD_MODAL";

export const TOOGLE_USER_MODAL = "TOOGLE_USER_MODAL";
export const TOOGLE_DOSSIER_MODAL = "TOOGLE_DOSSIER_MODAL";
export const TOOGLE_PROPRIETE_MODAL = "TOOGLE_PROPRIETE_MODAL";

export const SET_PROPRIETE_ADD_MODAL = "SET_PROPRIETE_ADD_MODAL";
export const SET_CLIENT_ADD_MODAL = "SET_CLIENT_ADD_MODAL";
export const SET_CHASSEUR_ADD_MODAL = "SET_CHASSEUR_ADD_MODAL";

export const SET_REGISTER_DATA = "SET_REGISTER_DATA";