export const GET_PROPRIETE = "GET_PROPRIETE";
export const ADD_PROPRIETE = "ADD_PROPRIETE";
export const UPDATE_PROPRIETE = "UPDATE_PROPRIETE";
export const DELETE_PROPRIETE = "DELETE_PROPRIETE";

export const GET_DOSSIER = "GET_DOSSIER";
export const ADD_DOSSIER = "ADD_DOSSIER";
export const UPDATE_DOSSIER = "UPDATE_DOSSIER";
export const DELETE_DOSSIER = "DELETE_DOSSIER";

export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_MY_DATA = "GET_MY_DATA";
export const GET_LOGOUT = "GET_LOGOUT";
export const GET_ADRESSE_SITE = "GET_ADRESSE_SITE";

export const TOOGLE_LOADER = "TOOGLE_LOADER";
export const TOOGLE_CLIENT_ADD_MODAL = "TOOGLE_CLIENT_ADD_MODAL";
export const TOOGLE_CHASSEUR_ADD_MODAL = "TOOGLE_CHASSEUR_ADD_MODAL";
export const TOOGLE_PROPRIETE_ADD_MODAL = "TOOGLE_PROPRIETE_ADD_MODAL";

export const TOOGLE_USER_MODAL = "TOOGLE_USER_MODAL";
export const TOOGLE_DOSSIER_MODAL = "TOOGLE_DOSSIER_MODAL";
export const TOOGLE_PROPRIETE_MODAL = "TOOGLE_PROPRIETE_MODAL";

export const SET_PROPRIETE_ADD_MODAL = "SET_PROPRIETE_ADD_MODAL";